name: service_container
description: A services dependency container, fast and easy to use.
version: 1.0.2
repository: https://github.com/codelovercc/service_container

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  logging: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
